export const COUNTRY_CODE_MAP: { [key: string]: string } = {
  'USA': 'us',
  'United States': 'us',
  'Miami': 'us',
  'Italy': 'it',
  'Monaco': 'mc',
  'Canada': 'ca',
  'Spain': 'es',
  'Austria': 'at',
  'UK': 'gb',
  'United Kingdom': 'gb',
  'Hungary': 'hu',
  'Belgium': 'be',
  'Netherlands': 'nl',
  'Azerbaijan': 'az',
  'Singapore': 'sg',
  'Mexico': 'mx',
  'Brazil': 'br',
  'Qatar': 'qa',
  'UAE': 'ae',
  'United Arab Emirates': 'ae',
  'France': 'fr',
  'Germany': 'de',
  'Portugal': 'pt',
  'Russia': 'ru',
  'Turkey': 'tr',
  'Vietnam': 'vn',
  'South Africa': 'za',
  'Argentina': 'ar',
  'Korea': 'kr',
  'India': 'in',
  'Malaysia': 'my',
  'China': 'cn',
  'Bahrain': 'bh',
  'Saudi Arabia': 'sa',
  'Japan': 'jp',
  'Australia': 'au',
  'Mexico City': 'mx',
  'Great Britain': 'gb',
  'Europe': 'eu',
  'Valencia': 'es',
  'Abu Dhabi': 'ae',
};

export function getCountryCode(country: string): string {
  return COUNTRY_CODE_MAP[country] || '';
}
